server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: msb
    url: jdbc:mysql://localhost:3306/xm_mental_health?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fileBaseUrl: http://localhost:${server.port}

logging:
  level:
    # 降低 MyBatis 核心包的日志级别，减少 SQL 等详细信息的输出
    org.mybatis: WARN
    # 降低数据库连接池 HikariCP 的日志级别
    com.zaxxer.hikari: WARN
    # 配置你自己的业务包路径，提高其日志级别，以便显示操作相关的数据信息
    com.example: INFO  #项目的实际主包名
